# Generated by Django 5.0.1 on 2024-01-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='content',
            name='latin_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='content',
            name='location_found',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='content',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='main.tag'),
        ),
        migrations.AddField(
            model_name='content',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, to='main.like'),
        ),
    ]
