# Generated by Django 5.0.1 on 2024-01-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_like_alter_content_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='likes',
            field=models.ManyToManyField(blank=True, to='main.like'),
        ),
        migrations.AlterField(
            model_name='content',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main.tag'),
        ),
    ]
