# Generated by Django 5.0.1 on 2024-01-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_content_likes_alter_content_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='comment',
            field=models.ManyToManyField(blank=True, to='main.comment'),
        ),
    ]
