name: Deploy to VM GCP

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Push Docker Image
        run: |
          docker build -t frinzthecoder/frinzcatalog:latest .
          docker push frinzthecoder/frinzcatalog:latest

      - name: Use SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy
        run: |
          apk update && apk add openssh-client
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.GCP_USERNAME }}@${{ secrets.GCP_STATIC_IP }} "
            docker container rm -f frinzcatalog || true &&
            docker image rm -f frinzthecoder/frinzcatalog:latest || true &&
            docker run --name frinzcatalog --restart unless-stopped -d -p 80:8000 -e DJANGO_ENV=production frinzthecoder/frinzcatalog:latest"
